### ISSUE TITLE
Create Apps Endpoint

### ISSUE THREAD

**Issue by Clivern** [Clivern/Beetle#14]
```
GET /api/v1/cluster/<clusterName>/namespace/<namespaceName>/application
```

Cluster Configs

If only version (eg. `1.0.0` or `1.1.0`) will be provided to deployment & rollback endpoints
```yaml
    applications:
      -
        name: Toad App
        id: toad
        image: clivern/toad:release-[.Release]
```

If only version or version with suffix (eg. `1.0.0` or `release-1.1.0` or `version-1.0.0`) will be provided to deployment & rollback endpoints
```yaml
    applications:
      -
        name: Toad App
        id: toad
        image: clivern/toad:[.Release]
```

If the whole image will be provided (eg. `clivern/toad:1.0.0` or `clivern/toad:release-1.1.0` or `clivern/toad:version-1.0.0`) will be provided to deployment & rollback endpoints
```yaml
    applications:
      -
        name: Toad App
        id: toad
        image: [.Release]
```
